# Spendle

spring.datasource.url=jdbc:h2:mem:spendledb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console -> http://localhost:8080/h2-console
# JDBC URL to use when logging in: jdbc:h2:mem:spendledb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Server port (change if needed)
server.port=8080